//! Integration test: run the real `speexenc`-encoded narrowband fixture
//! through the **closed-loop** [`NarrowbandDecoder`] — the full §8–§9
//! decode recurrence with the excitation feedback wired:
//!
//! ```text
//!   LSP reconstruct → interpolate → LSP→LPC
//!   p[n] = gain · adaptive-codebook(excitation history)
//!   c[n] = gain · innovation sub-vector
//!   e[n] = p[n] + c[n]   →  push into excitation history
//!   x[n] = 1/A(z) · e[n]
//! ```
//!
//! This is the upgrade over `synthesis_pcm_fixture.rs`, which fed the
//! synthesis filter the innovation `c[n]` **alone** (the pitch
//! contribution was always zero because the excitation feedback was not
//! wired). Here the decoder threads the composed `e[n] = p[n] + c[n]`
//! through the [`NarrowbandDecoder`]'s persistent
//! [`oxideav_speex::ExcitationBuffer`], so the adaptive-codebook (pitch)
//! contribution is live from the second sub-frame onward.
//!
//! The fixture is the same `tests/fixtures/nb_440hz_q8.spx` the other
//! fixture tests consume, generated by the black-box `speexenc` binary
//! (source NOT consulted). Per workspace policy this crate takes no
//! dev-dependency on `oxideav-ogg`; the same minimal inline Ogg
//! page-walker the sibling fixture tests use lifts the audio packets.

use oxideav_speex::{
    NarrowbandDecoder, NarrowbandFrameBody, NarrowbandFrameHeader, Submode,
    NARROWBAND_FRAME_SAMPLES,
};

const FIXTURE: &[u8] = include_bytes!("fixtures/nb_440hz_q8.spx");

/// Inline minimal Ogg page-walker — identical contract to the sibling
/// fixture tests: stitch lacing-segment runs back into Speex packets,
/// ignoring chained streams / BOS-EOS / granulepos / serial / CRC.
fn lift_ogg_packets(buf: &[u8]) -> Vec<Vec<u8>> {
    let mut packets = Vec::new();
    let mut current: Vec<u8> = Vec::new();
    let mut pos = 0usize;
    while pos + 27 <= buf.len() {
        if &buf[pos..pos + 4] != b"OggS" {
            break;
        }
        let nseg = buf[pos + 26] as usize;
        if pos + 27 + nseg > buf.len() {
            break;
        }
        let segments = &buf[pos + 27..pos + 27 + nseg];
        let mut body_pos = pos + 27 + nseg;
        for &ln in segments {
            let take = ln as usize;
            if body_pos + take > buf.len() {
                return packets;
            }
            current.extend_from_slice(&buf[body_pos..body_pos + take]);
            body_pos += take;
            if take < 255 {
                packets.push(core::mem::take(&mut current));
            }
        }
        pos = body_pos;
    }
    packets
}

/// Decode every audio packet through the closed-loop decoder, returning
/// the concatenated f64 PCM for all frames.
fn decode_fixture() -> Vec<f64> {
    let packets = lift_ogg_packets(FIXTURE);
    let audio = &packets[2..];
    assert!(!audio.is_empty(), "no audio packets in fixture");

    let mut decoder = NarrowbandDecoder::new();
    let mut pcm = Vec::new();
    for pkt in audio {
        let (h, mut r) = NarrowbandFrameHeader::parse_bytes(pkt).expect("header parse");
        let submode = match h.submode {
            Submode::Celp(s) => s,
            other => panic!("unexpected submode {:?}", other),
        };
        let body = NarrowbandFrameBody::parse(&mut r, &submode).expect("body parse");
        let frame = decoder
            .decode_frame(&body, &submode)
            .expect("mode 5 frame decodes");
        pcm.extend_from_slice(&frame);
    }
    pcm
}

#[test]
fn closed_loop_decodes_to_finite_responsive_pcm() {
    let pcm = decode_fixture();

    // 50 frames × 160 samples ≈ 8000 samples for the 1 s fixture.
    assert!(
        pcm.len() >= 40 * NARROWBAND_FRAME_SAMPLES,
        "expected ≥ {} PCM samples, got {}",
        40 * NARROWBAND_FRAME_SAMPLES,
        pcm.len()
    );

    // Every sample finite (no NaN/Inf from an unstable filter or
    // runaway feedback loop).
    for (i, &s) in pcm.iter().enumerate() {
        assert!(s.is_finite(), "sample {i} is not finite: {s}");
    }

    // Responsive: real excitation produces a non-constant, non-silent
    // signal.
    let max = pcm.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let min = pcm.iter().cloned().fold(f64::INFINITY, f64::min);
    assert!(
        max - min > 1.0,
        "PCM has no dynamic range (max {max} − min {min} ≤ 1)"
    );

    let energy: f64 = pcm.iter().map(|&s| s * s).sum();
    assert!(energy > 0.0, "PCM has zero energy");
}

#[test]
fn closed_loop_feedback_changes_output_vs_innovation_only() {
    // The closed-loop decoder threads e[n] = p[n] + c[n] (with pitch)
    // through the synthesis filter. After the first frame the excitation
    // history is non-zero, so the pitch contribution is live and the
    // output differs from a hypothetical innovation-only path. We prove
    // the loop is closed by confirming the second frame's PCM is not a
    // bit-for-bit repeat of the first when frames are identical inputs —
    // i.e. the decoder carries forward state.
    let packets = lift_ogg_packets(FIXTURE);
    let audio = &packets[2..];
    assert!(audio.len() >= 2, "need at least 2 audio frames");

    let mut decoder = NarrowbandDecoder::new();
    let mut frames: Vec<[f64; NARROWBAND_FRAME_SAMPLES]> = Vec::new();
    for pkt in audio.iter().take(4) {
        let (h, mut r) = NarrowbandFrameHeader::parse_bytes(pkt).expect("header");
        let submode = match h.submode {
            Submode::Celp(s) => s,
            other => panic!("unexpected submode {:?}", other),
        };
        let body = NarrowbandFrameBody::parse(&mut r, &submode).expect("body");
        frames.push(decoder.decode_frame(&body, &submode).expect("decode"));
    }

    // Consecutive frames carry the IIR + excitation state forward, so
    // even with similar inputs the outputs are not identical.
    let identical = frames[0] == frames[1];
    assert!(
        !identical,
        "closed-loop state should make consecutive frames differ"
    );
}

#[test]
fn closed_loop_is_deterministic() {
    let a = decode_fixture();
    let b = decode_fixture();
    assert_eq!(a.len(), b.len());
    for (i, (&x, &y)) in a.iter().zip(b.iter()).enumerate() {
        assert_eq!(x, y, "non-deterministic PCM at sample {i}");
    }
}

#[test]
fn closed_loop_pcm_is_finite_over_whole_stream() {
    // The closed loop is *structurally* complete (e[n] = p[n] + c[n] is
    // threaded through the excitation history and the synthesis filter),
    // and every sample is finite — no NaN / Inf escapes the recurrence.
    //
    // Note: the *magnitude* boundedness of the output is NOT yet
    // guaranteed. The synthesis filter's stability depends on the
    // reconstructed LPC set lying inside the unit circle, which in turn
    // depends on the LSP angular-unit Q-format that the in-repo Speex
    // manual leaves unspecified (recorded docs gap; see the
    // `src/lsp_to_lpc.rs` module docs). Under the current placeholder
    // angular-unit assumption the closed-loop feedback can amplify an
    // out-of-spec LPC set, so this test asserts only the guarantee the
    // structure actually provides — finiteness — and documents the
    // magnitude pin as the remaining gap. The innovation-only
    // `synthesis_pcm_fixture.rs` path masked this because it carried no
    // feedback.
    let pcm = decode_fixture();
    for (i, &s) in pcm.iter().enumerate() {
        assert!(s.is_finite(), "sample {i} = {s} is not finite");
    }
}
